addGroup = "https://omegaup.com/api/user/addGroup/"
associateIdentity = "https://omegaup.com/api/user/associateIdentity/"
changePassword = "https://omegaup.com/api/user/changePassword/"
coderOfTheMonth = "https://omegaup.com/api/user/coderOfTheMonth/"
coderOfTheMonthList = "https://omegaup.com/api/user/coderOfTheMonthList/"
contestStats = "https://omegaup.com/api/user/contestStats/"

# Interesting stuff
create = "https://omegaup.com/api/user/create/"
generateOmiUsers = "https://omegaup.com/api/user/generateOmiUsers/"

listAssociatedIdentities = "https://omegaup.com/api/user/listAssociatedIdentities/"
listUnsolvedProblems = "https://omegaup.com/api/user/listUnsolvedProblems/"
login = "https://omegaup.com/api/user/login/"

#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
#login = "https://omegaup.com"
