# This is a basic workflow to help you get started with Actions

name: Format

# Controls when the action will run. 
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  Format:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Setup dependencies
        run: | 
          python -m pip install pipx
          python -m pipx ensurepath

      - name: Lint Action
        uses: wearerequired/lint-action@v1.10.0
        with:
          black: true
          black_command_prefix: "pipx run "
          
          auto_fix: true
          
          git_name: "${{ github.actor }}"
          git_email: "${{ github.actor }}@users.noreply.github.com"
          github_token: ${{ secrets.GITHUB_TOKEN }}
